const EVENTS = [
  {
    id: 1,
    title: "Dîner Secret",
    tag: "Gastronomie",
    date: "Samedi 5 juil. · 20h00",
    location: "Le Marais, Paris 3e",
    spots: "4 places restantes",
    description: "Une expérience gastronomique dans un lieu caché du Marais. Menu 5 services élaboré par un chef étoilé, accord mets-vins inclus.",
    color: "#FF6B6B",
    lat: 48.8620,
    lng: 2.3590,
    bookingUrl: "https://example.com/reservation/diner-secret",
    chat: [
      { author: "Hôte", avatar: "👨‍🍳", text: "Bonsoir ! Bienvenue dans la discussion de cette soirée. N'hésitez pas à poser vos questions.", time: "18:02" },
      { author: "Camille", avatar: "😊", text: "Est-ce que le menu est adapté aux végétariens ?", time: "18:15" },
      { author: "Hôte", avatar: "👨‍🍳", text: "Oui absolument, une option végétarienne complète est disponible sur demande lors de la réservation 🌿", time: "18:17" },
      { author: "Lucas", avatar: "🙋‍♂️", text: "C'est inclus dans le prix le parking ?", time: "18:34" },
      { author: "Hôte", avatar: "👨‍🍳", text: "Pas de parking inclus, mais il y a plusieurs parkings à moins de 5 min à pied. Métro Saint-Sébastien–Froissart à 3 min recommandé !", time: "18:36" },
    ]
  },
  {
    id: 2,
    title: "Cocktail Rooftop",
    tag: "Cocktails",
    date: "Vendredi 4 juil. · 19h30",
    location: "République, Paris 11e",
    spots: "12 places restantes",
    description: "Soirée cocktails au sommet d'un immeuble haussmannien avec vue panoramique sur Paris. DJ set ambiance lounge, cocktails signature.",
    color: "#845EC2",
    lat: 48.8674,
    lng: 2.3628,
    bookingUrl: "https://example.com/reservation/cocktail-rooftop",
    chat: [
      { author: "Hôte", avatar: "🍹", text: "Salut tout le monde ! Vendredi s'annonce superbe côté météo, parfait pour notre rooftop 🌇", time: "12:00" },
      { author: "Sophia", avatar: "🥂", text: "Est-ce qu'il y a des options sans alcool ?", time: "12:45" },
      { author: "Hôte", avatar: "🍹", text: "Oui ! On a toute une carte de mocktails maison 🍊🌿", time: "12:47" },
      { author: "Antoine", avatar: "😄", text: "Le dress code c'est quoi ? Plutôt casual ou chic ?", time: "13:10" },
      { author: "Hôte", avatar: "🍹", text: "Smart casual recommandé — élégant mais pas trop formel. On est sur un rooftop after tout 😎", time: "13:12" },
    ]
  },
  {
    id: 3,
    title: "Soirée Jazz",
    tag: "Musique",
    date: "Jeudi 3 juil. · 21h00",
    location: "Saint-Germain, Paris 6e",
    spots: "6 places restantes",
    description: "Jazz live dans une cave voûtée du XVIIe siècle. Quartet exceptionnel pour une nuit à l'ambiance new-yorkaise. Tapas et vins nature au programme.",
    color: "#00B4D8",
    lat: 48.8534,
    lng: 2.3350,
    bookingUrl: "https://example.com/reservation/soiree-jazz",
    chat: [
      { author: "Hôte", avatar: "🎷", text: "Bienvenue ! Le quartet de ce jeudi est composé de musiciens du Conservatoire de Paris. Ce sera une belle soirée 🎶", time: "09:30" },
      { author: "Marie", avatar: "🎵", text: "Est-ce que c'est accessible PMR ?", time: "10:05" },
      { author: "Hôte", avatar: "🎷", text: "Malheureusement la cave a des marches à l'entrée, ce n'est pas accessible en fauteuil roulant. Désolé pour la gêne.", time: "10:08" },
      { author: "Théo", avatar: "😍", text: "J'ai été au précédent, c'était incroyable. Hâte d'y retourner !", time: "11:22" },
      { author: "Hôte", avatar: "🎷", text: "Super, on est ravis de te revoir Théo ! 🙌", time: "11:25" },
    ]
  },
  {
    id: 4,
    title: "Dégustation Vins Nature",
    tag: "Œnologie",
    date: "Dimanche 6 juil. · 17h00",
    location: "Batignolles, Paris 17e",
    spots: "10 places restantes",
    description: "Découvrez 8 vins nature soigneusement sélectionnés chez des vignerons indépendants, guidés par une sommelière certifiée. Accords fromages & charcuteries.",
    color: "#F4845F",
    lat: 48.8848,
    lng: 2.3180,
    bookingUrl: "https://example.com/reservation/degustation-vins",
    chat: [
      { author: "Hôte", avatar: "🍷", text: "Hello ! Pour cette session on a sélectionné des vignerons du Jura, de Loire et du Languedoc. Des régions magnifiques 🌿", time: "14:00" },
      { author: "Elise", avatar: "🍇", text: "Est-ce qu'on repart avec les références des bouteilles ?", time: "14:30" },
      { author: "Hôte", avatar: "🍷", text: "Oui ! Chaque participant reçoit une fiche complète avec les références, contacts des vignerons et liens de commande directe 📋", time: "14:33" },
      { author: "Paul", avatar: "🤔", text: "C'est ouvert aux débutants ? Je connais pas grand chose au vin nature...", time: "15:00" },
      { author: "Hôte", avatar: "🍷", text: "C'est fait pour ça ! On commence par les bases. Aucune connaissance requise, juste de la curiosité 😊", time: "15:02" },
    ]
  },
  {
    id: 5,
    title: "Cinéma Plein Air",
    tag: "Cinéma",
    date: "Mardi 8 juil. · 22h00",
    location: "Butte-aux-Cailles, Paris 13e",
    spots: "20 places restantes",
    description: "Projection en plein air d'un classique du cinéma français dans un jardin secret. Couvertures fournies, pop-corn artisanal et boissons fraîches.",
    color: "#2EC4B6",
    lat: 48.8284,
    lng: 2.3506,
    bookingUrl: "https://example.com/reservation/cinema-plein-air",
    chat: [
      { author: "Hôte", avatar: "🎬", text: "Bonsoir ! Le film de la soirée sera révélé uniquement sur place — ambiance surprise garantie 🎞️", time: "20:00" },
      { author: "Nina", avatar: "🍿", text: "Est-ce qu'on peut apporter notre propre pique-nique ?", time: "20:15" },
      { author: "Hôte", avatar: "🎬", text: "Oui, les pique-niques sont les bienvenus ! On s'occupe juste des boissons et du pop-corn 🥤", time: "20:17" },
      { author: "Marc", avatar: "😅", text: "Et si il pleut ?", time: "20:40" },
      { author: "Hôte", avatar: "🎬", text: "En cas de pluie on reporte au lendemain et on vous prévient par email 24h avant. Les places restent valables ☔", time: "20:42" },
    ]
  }
];
